using BigRedProf.Data.PackRatCompiler.Internal;
using BigRedProf.Data.PackRatCompiler.Internal.Symbols;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace BigRedProf.Data.PackRatCompiler
{
	/// <summary>
	/// This class can generate a <see cref="PackRat"/> class from a given model.
	/// </summary>
	public class PackRatGenerator
	{
		#region fields
		private ICompilationContext _compilationContext;
		#endregion

		#region constructors
		public PackRatGenerator(ICompilationContext compilationContext)
		{
			_compilationContext = compilationContext;
		}
		#endregion

		#region methods
		/// <summary>
		/// Generates a <see cref="PackRat"/> from the specified input model and writes it
		/// to the specified output model stream.
		/// </summary>
		/// <param name="inputModel">The model.</param>
		/// <param name="outputPackRatStream">The generated pack rat.</param>
		public void GeneratePackRat(INamedTypeSymbol inputModel, Stream outputPackRatStream)
		{
			if (inputModel == null)
				throw new ArgumentNullException(nameof(inputModel));

			if (outputPackRatStream == null)
				throw new ArgumentNullException(nameof(outputPackRatStream));

			using (CSharpWriter writer = new CSharpWriter(outputPackRatStream))
			{
				WriteFile(inputModel, writer);
			}
		}
		#endregion

		#region private methods
		private void WriteFile(INamedTypeSymbol modelClass, CSharpWriter writer)
		{
			writer.WriteLine("// <auto-generated/>");

			string @namespace = modelClass.ContainingNamespace.ToDisplayString();
			writer.WriteLine($"namespace {@namespace}");
			writer.WriteOpeningCurlyBrace();
			WritePackRatClass(modelClass, writer);
			writer.WriteClosingCurlyBrace();
		}

		private void WritePackRatClass(INamedTypeSymbol modelClass, CSharpWriter writer)
		{
			string className = modelClass.Name + "PackRat";
			writer.WriteLine($"public class {className}");
			writer.WriteOpeningCurlyBrace();
			IList<PackFieldInfo> fields = SymbolHelper.GetPackRatFields(modelClass);
			for(int i = 0; i < fields.Count; ++i)
			{
				PackFieldInfo field = fields[i];

				if(field.Position != i + 1)
				{
					_compilationContext.ReportError(
						CompilerError.InvalidFieldPosition,
						String.Format(
							"Field '{0}' in model '{1}' has invalid field position. Expected: {2}. Actual: {3}",
							field.Name,
							modelClass.ToDisplayString(),
							i + 1,
							field.Position
						),
						modelClass.ContainingModule.ToDisplayString(),
						field.SourceLineNumber,
						field.SourceColumn
					);
				}

				WritePackRatField(modelClass, field, writer);

				if (field.Position == 1)
				{
					writer.WriteLine(string.Empty);
				}
			}
			writer.WriteClosingCurlyBrace();
		}

		private void WritePackRatField(
			ITypeSymbol modelClass, 
			PackFieldInfo field,
			CSharpWriter writer
		)
		{
			writer.WriteLine($"// {field.Name}");
		}
		#endregion
	}
}
