// <auto-generated/>

using BigRedProf.Data.Core;

namespace BigRedProf.Data.PackRatCompiler.Test._Resources.Models
{
	[AssemblyPackRat("d4e8f1a2-3b5c-4d6e-8f90-1a2b3c4d5e6f")]
	public sealed class MixedListTestModelPackRat : PackRat<MixedListTestModel>
	{
		public MixedListTestModelPackRat(IPiedPiper piedPiper)
			: base(piedPiper)
		{
		}

		public override void PackModel(CodeWriter writer, MixedListTestModel model)
		{
			// ListProperty
			PiedPiper.PackList<string>(
				writer,
				model.ListProperty,
				"9cdf52b4-4c47-4b6d-bc17-34f33312b7a7",
				false,
				false,
				ByteAligned.Yes
			);

			// ListField
			PiedPiper.PackList<int>(
				writer,
				model.ListField,
				"ffdb57bb-be6b-4cc3-a0f6-48596c8a8b2b",
				false,
				false,
				ByteAligned.No
			);

			// NullableListPropertyOfNullableElements
			PiedPiper.PackList<string>(
				writer,
				model.NullableListPropertyOfNullableElements,
				"9cdf52b4-4c47-4b6d-bc17-34f33312b7a7",
				true,
				true,
				ByteAligned.No
			);

			// NullableListField
			PiedPiper.PackList<int>(
				writer,
				model.NullableListField,
				"ffdb57bb-be6b-4cc3-a0f6-48596c8a8b2b",
				true,
				false,
				ByteAligned.Yes
			);
		}

		public override MixedListTestModel UnpackModel(CodeReader reader)
		{
			MixedListTestModel model = new MixedListTestModel();

			// ListProperty
			model.ListProperty = PiedPiper.UnpackList<string>(
				reader,
				"9cdf52b4-4c47-4b6d-bc17-34f33312b7a7",
				false,
				false,
				ByteAligned.Yes
			);

			// ListField
			model.ListField = PiedPiper.UnpackList<int>(
				reader,
				"ffdb57bb-be6b-4cc3-a0f6-48596c8a8b2b",
				false,
				false,
				ByteAligned.No
			);

			// NullableListPropertyOfNullableElements
			model.NullableListPropertyOfNullableElements = PiedPiper.UnpackList<string>(
				reader,
				"9cdf52b4-4c47-4b6d-bc17-34f33312b7a7",
				true,
				true,
				ByteAligned.No
			);

			// NullableListField
			model.NullableListField = PiedPiper.UnpackList<int>(
				reader,
				"ffdb57bb-be6b-4cc3-a0f6-48596c8a8b2b",
				true,
				false,
				ByteAligned.Yes
			);

			return model;
		}
	}
}
