// <auto-generated/>

using BigRedProf.Data.Core;

namespace BigRedProf.Data.PackRatCompiler.Test._Resources.Models
{
	[AssemblyPackRat("b8a0492a-c5e6-4955-819b-f47797005105")]
	public sealed class NullableTestModelPackRat : PackRat<NullableTestModel>
	{
		public NullableTestModelPackRat(IPiedPiper piedPiper)
			: base(piedPiper)
		{
		}

		public override void PackModel(CodeWriter writer, NullableTestModel model)
		{
			// ExplicitlyNullableField
			PiedPiper.PackNullableModel<string>(writer, model.ExplicitlyNullableField, "9cdf52b4-4c47-4b6d-bc17-34f33312b7a7", ByteAligned.No);

			// ExplicitlyNonNullableField
			PiedPiper.GetPackRat<string>("9cdf52b4-4c47-4b6d-bc17-34f33312b7a7")
				.PackModel(writer, model.ExplicitlyNonNullableField);

			// ImplicitlyNullableField
			PiedPiper.PackNullableModel<string>(writer, model.ImplicitlyNullableField, "9cdf52b4-4c47-4b6d-bc17-34f33312b7a7", ByteAligned.No);

			// ImplicitlyNonNullableField
			PiedPiper.GetPackRat<string>("9cdf52b4-4c47-4b6d-bc17-34f33312b7a7")
				.PackModel(writer, model.ImplicitlyNonNullableField);
		}

		public override NullableTestModel UnpackModel(CodeReader reader)
		{
			NullableTestModel model = new NullableTestModel();

			// ExplicitlyNullableField
			model.ExplicitlyNullableField = PiedPiper.UnpackNullableModel<string>(reader, "9cdf52b4-4c47-4b6d-bc17-34f33312b7a7", ByteAligned.No);

			// ExplicitlyNonNullableField
			model.ExplicitlyNonNullableField = PiedPiper.GetPackRat<string>("9cdf52b4-4c47-4b6d-bc17-34f33312b7a7")
				.UnpackModel(reader);

			// ImplicitlyNullableField
			model.ImplicitlyNullableField = PiedPiper.UnpackNullableModel<string>(reader, "9cdf52b4-4c47-4b6d-bc17-34f33312b7a7", ByteAligned.No);

			// ImplicitlyNonNullableField
			model.ImplicitlyNonNullableField = PiedPiper.GetPackRat<string>("9cdf52b4-4c47-4b6d-bc17-34f33312b7a7")
				.UnpackModel(reader);

			return model;
		}
	}
}
