// <auto-generated/>

using BigRedProf.Data.Core;

namespace BigRedProf.Data.PackRatCompiler.Test._Resources.Models
{
	[AssemblyPackRat("2f5c8f1a-6b2d-4a77-9d0e-84c3a51b7e60")]
	public sealed class RetiredFieldTestModelPackRat : PackRat<RetiredFieldTestModel>
	{
		public RetiredFieldTestModelPackRat(IPiedPiper piedPiper)
			: base(piedPiper)
		{
		}

		public override void PackModel(CodeWriter writer, RetiredFieldTestModel model)
		{
			// Height
			PiedPiper.GetPackRat<int>("ffdb57bb-be6b-4cc3-a0f6-48596c8a8b2b")
				.PackModel(writer, model.Height);

			// Weight
			PiedPiper.GetPackRat<int>("ffdb57bb-be6b-4cc3-a0f6-48596c8a8b2b")
				.PackModel(writer, model.Weight);
		}

		public override RetiredFieldTestModel UnpackModel(CodeReader reader)
		{
			RetiredFieldTestModel model = new RetiredFieldTestModel();

			// Height
			model.Height = PiedPiper.GetPackRat<int>("ffdb57bb-be6b-4cc3-a0f6-48596c8a8b2b")
				.UnpackModel(reader);

			// Weight
			model.Weight = PiedPiper.GetPackRat<int>("ffdb57bb-be6b-4cc3-a0f6-48596c8a8b2b")
				.UnpackModel(reader);

			return model;
		}
	}
}
