// <auto-generated/>

using BigRedProf.Data.Core;

namespace BigRedProf.Data.PackRatCompiler.Test._Resources.Models
{
	[AssemblyPackRat("54f0c71b-af41-4a25-ac7f-4e0e9741a818")]
	public sealed class TokenTestModelPackRat : PackRat<TokenTestModel>
	{
		public TokenTestModelPackRat(IPiedPiper piedPiper)
			: base(piedPiper)
		{
		}

		public override void PackModel(CodeWriter writer, TokenTestModel model)
		{
			// StringAsValue
			PiedPiper.GetPackRat<string>("cf1820e1-86b7-4e1c-909e-c9b874996e58")
				.PackModel(writer, model.StringAsValue);

			// StringAsToken
			PiedPiper.GetPackRat<string>("e9ab0764-2e47-42dc-860d-0ba1573b728f")
				.PackModel(writer, model.StringAsToken);
		}

		public override TokenTestModel UnpackModel(CodeReader reader)
		{
			TokenTestModel model = new TokenTestModel();

			// StringAsValue
			model.StringAsValue = PiedPiper.GetPackRat<string>("cf1820e1-86b7-4e1c-909e-c9b874996e58")
				.UnpackModel(reader);

			// StringAsToken
			model.StringAsToken = PiedPiper.GetPackRat<string>("e9ab0764-2e47-42dc-860d-0ba1573b728f")
				.UnpackModel(reader);

			return model;
		}
	}
}
