<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net8.0</TargetFramework>
		<PackageType>DotNetCliTool</PackageType>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<!-- dotnet tool settings -->
	<PropertyGroup>
		<PackAsTool>true</PackAsTool>
		<PackageId>BigRedProf.Data.PackRatCompiler</PackageId>
		<ToolCommandName>prc</ToolCommandName>
		<GeneratePackageOnBuild>true</GeneratePackageOnBuild>
		<AssemblyName>prc</AssemblyName>

		<Title>PackRat Compiler</Title>
		<Description>The prc command-line tool: generates BigRedProf pack rats from annotated C# models.</Description>
		<PackageTags>bigredprof;codegen;packrat;dotnet-tool</PackageTags>
	</PropertyGroup>
	
	<ItemGroup>
	  <PackageReference Include="CommandLineParser" />
	  <PackageReference Include="Microsoft.Build.Locator" />
	  <PackageReference Include="Microsoft.CodeAnalysis" />
	  <PackageReference Include="Microsoft.CodeAnalysis.Common" />
	  <PackageReference Include="Microsoft.CodeAnalysis.Workspaces.MSBuild" />
	</ItemGroup>
	
	<ItemGroup>
	  <ProjectReference Include="..\Core\BigRedProf.Data.Core.csproj" />
	</ItemGroup>

</Project>
