// <auto-generated/>

using BigRedProf.Data;

namespace BigRedProf.Data.PackRatCompiler.Test._Resources.Models
{
	[AssemblyPackRat("c3b5a06c-da78-4f48-863f-455dfbd339f6")]
	public sealed class ListTestModelPackRat : PackRat<ListTestModel>
	{
		private readonly IPiedPiper _piedPiper;

		public ListTestModelPackRat(IPiedPiper piedPiper)
			: base(piedPiper)
		{
		}

		public override void PackModel(CodeWriter writer, ListTestModel model)
		{
			// List
			_piedPiper.PackList<string>(
				writer,
				model.List,
				"9CDF52B4-4C47-4B6D-BC17-34F33312B7A7",
				false,
				false,
				ByteAligned.Yes
			);

			// NullableList
			_piedPiper.PackList<string>(
				writer,
				model.NullableList,
				"9CDF52B4-4C47-4B6D-BC17-34F33312B7A7",
				true,
				false,
				ByteAligned.No
			);

			// ListOfNullableElements
			_piedPiper.PackList<string>(
				writer,
				model.ListOfNullableElements,
				"9CDF52B4-4C47-4B6D-BC17-34F33312B7A7",
				false,
				true,
				ByteAligned.No
			);

			// NullableListOfNullableElements
			_piedPiper.PackList<string>(
				writer,
				model.NullableListOfNullableElements,
				"9CDF52B4-4C47-4B6D-BC17-34F33312B7A7",
				true,
				true,
				ByteAligned.Yes
			);
		}

		public override ListTestModel UnpackModel(CodeReader reader)
		{
			ListTestModel model = default;

			// List
			model.List = _piedPiper.UnpackList<string>(
				reader,
				"9CDF52B4-4C47-4B6D-BC17-34F33312B7A7",
				false,
				false,
				ByteAligned.Yes
			);

			// NullableList
			model.NullableList = _piedPiper.UnpackList<string>(
				reader,
				"9CDF52B4-4C47-4B6D-BC17-34F33312B7A7",
				true,
				false,
				ByteAligned.No
			);

			// ListOfNullableElements
			model.ListOfNullableElements = _piedPiper.UnpackList<string>(
				reader,
				"9CDF52B4-4C47-4B6D-BC17-34F33312B7A7",
				false,
				true,
				ByteAligned.No
			);

			// NullableListOfNullableElements
			model.NullableListOfNullableElements = _piedPiper.UnpackList<string>(
				reader,
				"9CDF52B4-4C47-4B6D-BC17-34F33312B7A7",
				true,
				true,
				ByteAligned.Yes
			);

			return model;
		}
	}
}
