// <auto-generated/>

using BigRedProf.Data;

namespace BigRedProf.Data.PackRatCompiler.Test._Resources.Models
{
	public sealed class ListTestModelPackRat : PackRat<ListTestModel>
	{
		private readonly IPiedPiper _piedPiper;

		public ListTestModelPackRat(IPiedPiper piedPiper)
		{
			_piedPiper = piedPiper;
		}

		public override void PackModel(CodeWriter writer, ListTestModel model)
		{
			// List
			_piedPiper.PackList<string>(
				writer,
				model.List,
				"9CDF52B4-4C47-4B6D-BC17-34F33312B7A7",
				false,
				false,
				ByteAligned.Yes);

			// NullableList
			_piedPiper.PackList<string>(
				writer,
				model.List,
				"9CDF52B4-4C47-4B6D-BC17-34F33312B7A7",
				true,
				false,
				ByteAligned.Yes);

			// ListWithNullableElements
			_piedPiper.PackList<string>(
				writer,
				model.List,
				"9CDF52B4-4C47-4B6D-BC17-34F33312B7A7",
				false,
				true,
				ByteAligned.Yes);

			// NonNullableListWithNullableElements
			_piedPiper.PackList<string>(
				writer,
				model.List,
				"9CDF52B4-4C47-4B6D-BC17-34F33312B7A7",
				true,
				true,
				ByteAligned.Yes);
		}

		public override ListTestModel UnpackModel(CodeReader reader)
		{
			ListTestModel model = default;

			// List
			model.List = _piedPiper.UnpackList<string>(
				reader,
				"9CDF52B4-4C47-4B6D-BC17-34F33312B7A7",
				false,
				false,
				ByteAligned.Yes
			);

			// NullableList
			model.List = _piedPiper.UnpackList<string>(
				reader,
				"9CDF52B4-4C47-4B6D-BC17-34F33312B7A7",
				true,
				false,
				ByteAligned.Yes
			);

			// ListWithNullableElements
			model.List = _piedPiper.UnpackList<string>(
				reader,
				"9CDF52B4-4C47-4B6D-BC17-34F33312B7A7",
				false,
				true,
				ByteAligned.Yes
			);

			// NullableListWithNullableElements
			model.List = _piedPiper.UnpackList<string>(
				reader,
				"9CDF52B4-4C47-4B6D-BC17-34F33312B7A7",
				true,
				true,
				ByteAligned.Yes
			);

			return model;
		}
	}
}
