// <auto-generated/>

using BigRedProf.Data;

namespace BigRedProf.Data.PackRatCompiler.Test._Resources.Models
{
	[AssemblyPackRat("2993c2cf-3d21-4d94-94af-091cfc5594ad")]
	public sealed class ModelWithEnumPackRat : PackRat<ModelWithEnum>
	{
		public ModelWithEnumPackRat(IPiedPiper piedPiper)
			: base(piedPiper)
		{
		}

		public override void PackModel(CodeWriter writer, ModelWithEnum model)
		{
			// Color1
			PiedPiper.GetPackRat<int>("FFDB57BB-BE6B-4CC3-A0F6-48596C8A8B2B")
				.PackModel(writer, (int) model.Color1);

			// Color2
			PiedPiper.GetPackRat<int>("303EEDD7-2F7F-4D6A-9E94-DE3523322B33")
				.PackModel(writer, (int) model.Color2);
		}

		public override ModelWithEnum UnpackModel(CodeReader reader)
		{
			ModelWithEnum model = new ModelWithEnum();

			// Color1
			model.Color1 = (BigRedProf.Data.PackRatCompiler.Test._Resources.Models.ColorHexagon) PiedPiper.GetPackRat<int>("FFDB57BB-BE6B-4CC3-A0F6-48596C8A8B2B")
				.UnpackModel(reader);

			// Color2
			model.Color2 = (BigRedProf.Data.PackRatCompiler.Test._Resources.Models.ColorHexagon) PiedPiper.GetPackRat<int>("303EEDD7-2F7F-4D6A-9E94-DE3523322B33")
				.UnpackModel(reader);

			return model;
		}
	}
}
