// <auto-generated/>

using BigRedProf.Data;

namespace BigRedProf.Data.PackRatCompiler.Test._Resources.Models
{
	[AssemblyPackRat("b8a0492a-c5e6-4955-819b-f47797005105")]
	public sealed class NullableTestModelPackRat : PackRat<NullableTestModel>
	{
		public NullableTestModelPackRat(IPiedPiper piedPiper)
			: base(piedPiper)
		{
		}

		public override void PackModel(CodeWriter writer, NullableTestModel model)
		{
			// NullableField
			PiedPiper.GetPackRat<string>("9CDF52B4-4C47-4B6D-BC17-34F33312B7A7")
				.PackModel(writer, model.NullableField);

			// NonNullableField
			PiedPiper.GetPackRat<string>("9CDF52B4-4C47-4B6D-BC17-34F33312B7A7")
				.PackModel(writer, model.NonNullableField);
		}

		public override NullableTestModel UnpackModel(CodeReader reader)
		{
			NullableTestModel model = default;

			// NullableField
			model.NullableField = PiedPiper.GetPackRat<string>("9CDF52B4-4C47-4B6D-BC17-34F33312B7A7")
				.UnpackModel(reader);

			// NonNullableField
			model.NonNullableField = PiedPiper.GetPackRat<string>("9CDF52B4-4C47-4B6D-BC17-34F33312B7A7")
				.UnpackModel(reader);

			return model;
		}
	}
}
