// <auto-generated/>

using BigRedProf.Data;

namespace BigRedProf.Data.PackRatCompiler.Test._Resources.Models
{
	[AssemblyPackRat("d3499bac-fb5d-4407-8d28-e32ed37898c6")]
	public sealed class PointPackRat : PackRat<Point>
	{
		public PointPackRat(IPiedPiper piedPiper)
			: base(piedPiper)
		{
		}

		public override void PackModel(CodeWriter writer, Point model)
		{
			// X
			PiedPiper.GetPackRat<int>("ffdb57bb-be6b-4cc3-a0f6-48596c8a8b2b")
				.PackModel(writer, model.X);

			// Y
			PiedPiper.GetPackRat<int>("43")
				.PackModel(writer, model.Y);
		}

		public override Point UnpackModel(CodeReader reader)
		{
			Point model = new Point();

			// X
			model.X = PiedPiper.GetPackRat<int>("ffdb57bb-be6b-4cc3-a0f6-48596c8a8b2b")
				.UnpackModel(reader);

			// Y
			model.Y = PiedPiper.GetPackRat<int>("43")
				.UnpackModel(reader);

			return model;
		}
	}
}
