// <auto-generated/>

using BigRedProf.Data;

namespace prt.A.B.C
{
	public sealed class PointPackRat : PackRat<Point>
	{
		private readonly IPiedPiper _piedPiper;

		public PointPackRat(IPiedPiper piedPiper)
		{
			_piedPiper = piedPiper;
		}

		public override void PackModel(CodeWriter writer, Point model)
		{
			// X

			// Y
		}

		public override Point UnpackModel(CodeReader reader)
		{
			// X

			// Y
		}
	}
}
